name: Test-Build
on:
  push:
    branches:
      - main
jobs: 
  test-api:
    runs-on: ubuntu-latest
    # Install node on server
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    # Install the newman command line utility and also install the html extra reporter
    - name: Install newman
      run:
        npm install -g newman
        npm install -g newman-reporter-htmlextra
    # Make directory to upload the test results
    - name: Make directory for results
      run: mkdir -p testResults
