name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      # Копируем базу данных из резервной копии
      - name: Copy backup DB
        run: cp mockApi/db_back_up.yaml mockApi/db_stage.yaml

      # Выводим содержимое базы для проверки (отладка)
      - name: Debug DB file content
        run: cat mockApi/db_stage.yaml

      # Запускаем API сервер в фоновом режиме
      - name: Start API server
        run: npx yaml-server --hotReload=off --autoStart=off --port 3000 --database ./mockApi/db_stage.yaml &

      # Ожидаем, пока сервер действительно запустится и ответит по нужному эндпоинту
      - name: Wait for API to be ready
        run: |
          for i in {1..15}; do
            status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/products/9)
            if [ "$status" -eq "200" ]; then
              echo "API is ready with status code $status"
              exit 0
            else
              echo "Waiting for API... attempt $i, got status $status"
              sleep 2
            fi
          done
          echo "API did not become ready in time"
          exit 1

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests
        run: newman run new-store.json --environment new-store_environment.json
