name: Test-Build

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Node.js
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Start Server
        run: npm start & # Run server on background
      
      - name: wait for server to be ready
        run: |
          timeout 10 bash -c 'until echo > /dev/tcp/127.0.0.1/3000; do sleep 1; done'

      # Install Newman and the htmlextra reporter
      - name: Install Newman and Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Create directory for results
      - name: Create results directory
        run: mkdir -p testResults

      # Run Postman collection with Newman
      - name: Run Postman Collection
        run: |
          newman run store.collectionv2.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darktheme

      # Upload the test results as an artifact
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: testResults
