name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
        shell: pwsh

      - name: Ensure testResults directory
        run: New-Item -ItemType Directory -Path testResults -Force
        shell: pwsh

      - name: Run POSTMAN collection
        run: newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme
        shell: pwsh

      - name: List testResults directory
        run: Get-ChildItem -Path testResults
        shell: pwsh

      - name: Output the run Details
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: testResults
