name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Start mock API server
        run: npm run tern-on-api &
      
      - name: Wait for API to be ready
        run: sleep 10

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests
        run: newman run new-store.json --environment new-store_environment.json
