name: Test-Build

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest  # Можно использовать Linux-агент, или Windows, если нужно

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Устанавливаем Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Устанавливаем необходимые пакеты (newman, репортеры)
      - name: Install dependencies
        run: |
          npm install -g newman newman-reporter-htmlextra
        shell: bash

      # Шаг для запуска сервера
      - name: Start API server
        run: |
          cp mockApi/db_back_up.yaml mockApi/db_stage.yaml
          npx yaml-server --hotReload=off --autoStart=off --port 3000 --database ./mockApi/db_stage.yaml &
        shell: bash

      # Шаг для выполнения коллекции Postman с использованием Newman
      - name: Run POSTMAN collection
        run: |
          newman run storev2.collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme
        shell: bash

      # Шаг для вывода отчета о выполнении тестов
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: testResults/htmlreport.html
