name: Test-Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t newman_app .
        shell: bash

      # 3. Start API Server in Docker
      - name: Start API Server
        run: |
          docker run -d -p 3000:3000 --name newman_container newman_app
        shell: bash

      # 4. Ensure testResults directory exists
      - name: Ensure testResults directory
        run: mkdir -p testResults
        shell: bash

      # 5. Run POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          docker run -d --name newman_app -p 3001:3000 newman_app
          docker exec newman_app newman run /app/store.collectionv2.json -r htmlextra --reporter-htmlextra-export /app/testResults/htmlreport.html --reporter-htmlextra-darkTheme
        shell: bash

      # 6. List contents of testResults directory
      - name: List testResults directory
        run: ls -la testResults
        shell: bash

      # 7. Upload report as artifact
      - name: Upload Newman Report
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: testResults

      # 8. Clean up Docker
      - name: Clean up Docker
        run: |
          docker stop newman_app
          docker rm newman_app
        shell: bash
