name: Test-Build
on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Node.js
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Install Newman and reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
        shell: pwsh

      # Start API Server in Docker
      - name: Start API Server
        run: |
          docker run -d -p 3000:3000 --name api-server newman_app
        shell: pwsh

      # Ensure testResults directory exists
      - name: Ensure testResults directory
        run: New-Item -ItemType Directory -Path testResults -Force
        shell: pwsh

      # Run POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run store.collectionv2.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme
        shell: pwsh

      # List contents of testResults directory
      - name: List testResults directory
        run: Get-ChildItem -Path testResults
        shell: pwsh

      # Upload report as artifact
      - name: Upload Newman Report
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: testResults

      # Stop and remove Docker container
      - name: Clean up Docker
        run: |
          docker stop api-server
          docker rm api-server
        shell: pwsh
